# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FromU' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
pod 'KakaoSDKAuth'  # 사용자 인증
pod 'KakaoSDKUser'  # 카카오 로그인, 사용자 관리
pod 'KakaoSDKTalk'  # 친구, 메시지(카카오톡)
pod 'KakaoSDKStory'  # 카카오스토리 
pod 'KakaoSDKShare'  # 메시지(카카오톡 공유)
pod 'KakaoSDKTemplate'  # 메시지 템플릿 
pod 'KakaoSDKNavi'  # 카카오내비 
pod 'Moya'
pod 'SwiftKeychainWrapper'
pod 'FSCalendar'
pod 'Kingfisher'
pod 'lottie-ios'
pod 'AdvancedPageControl'

  # Pods for FromU
  target 'FromUTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FromUUITests' do
    # Pods for testing
  end

end

post_install do |installer|
 
installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end